name: gh_test
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest # use the lastest version of Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print message
        uses: echo 'It's work'
