name: gh_test
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest # use the lastest version of Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # uses = docker image

      - name: Print message
        run: |
          echo "It's work" #run use for linux command
          ls -la

  test_env_level:
    runs-on: ubuntu-latest
    environment:
      name: test_environment
    env:
      APP_SECRET: ${{ secrets.APP_SECRET }}
      APP_VAR: ${{ secrets.APP_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print message
        run: |
          echo "It's work"
          echo "APP_SECRET  : $APP_SECRET  "
          echo "APP_VAR  : $APP_VAR  "

  # remote_vps:
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #
  #     - name: Remote VPS (remote ssh using password)
  #       uses: appleboy/ssh-action@v1.2.1
  #       with: |
  #         host: ${{ secrets.HOST }}
  #         username: ${{ secrets.USERNAME }}
  #         password: ${{ secrets.PASSWORD }}
  #         port: ${{ secrets.PORT }}
  #         script: |
  #           whoami
  #           curl ifconfig.me
