name: gh_test
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest # use the lastest version of Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # uses = docker image

      - name: Print message
        run: |
          echo "It's work" #run use for linux command
          ls -la

  # remote_vps:
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #
  #     - name: Print message
  #       run: echo "It's work"
